@startuml
title
    Light Up Alarm Clock - Use cases
    v 1.0
end title

:User: as user
package "LUAC - Light Up Alarm Clock" {
    (Set Date & Time) as (SetDateTime)
    (Poll Temperature & Humidity Sensor) as (PollSensor)
    (Read Time, Date & Weather) as (Idle)
    (Set Alarm Clock #n) as (SetAl)
    (Set Alarm Wake up Time \n& Weekday) as (SetAlTime)
    (Set Alarm Sound) as (SetAlSound)
    (Set Alarm Light) as (SetAlLight)
    (Push Snooze Button) as (SnoozeBtn)
    (Delay Alarm) as (DelayAl)
    (Turn Reading-Light on) as (LightOn)
    (Turn Reading-Light off) as (LightOff)
    (Turn LCD Backlight on/off) as (LcdLightOnOff)
    (Dim Reading-Light) as (LightDim)
    (Set Sleep Timer) as (Sleep)

    left to right direction
    user --> (Idle)
    (Idle) <|-- (SetDateTime)
    (Idle) <|-- (PollSensor)
    user --> (SetAl)
    (SetAl) <|-- (SetAlTime)
    (SetAl) <|-- (SetAlSound)
    (SetAl) <|-- (SetAlLight)
    (SnoozeBtn) <|-- (LcdLightOnOff)
    (SnoozeBtn) <|-- (DelayAl)
    (Sleep) <|-- (LightDim)
    user --> (LightOn)
    user --> (LightOff)
    user --> (LightDim)
    user --> (SnoozeBtn)
    user --> (Sleep)
}
@enduml